//layout
import { ClerkProvider } from '@clerk/nextjs'
import Link from "next/link"
import { UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: 'BnB Website',
    description: 'BnB Website',
    type:"website",
    url:"",
    images:"",
}
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
    <nav>
      <Link href="/">Home</Link>
        <Link href="/pages/posts">Postings</Link>
        <Link href="/pages/hosts">Hosts</Link>
        <UserButton afterSignOutUrl='/'/>
    </nav>
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
